version: '3.8'
services:
  postgres_dev:
    container_name: drawy-studio
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - /var/lib/drawy-studio-db:/data/
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=drawy-studio-dev